repository: splicemachine/splicedocs-jekyll

compatible_version: 2.5   # Default is that all pages are backward compatible to 2.5

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: Splice Machine Docs
# this appears on the top navigation bar next to the home button

site_title: Splice Machine Documentation
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: Splice Machine, Inc
# this appears in the footer

github_editme_path: #splicemachine/splicedocs-jekyll/
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

disqus_shortname:
# if you're using disqus for comments, add the shortname here. if not, leave this value blank.

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4000
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

exclude:
  - .idea/
  - .gitignore
  - pages/_notyettopics
# these are the files and directories that jekyll will exclude from the build

feedback_subject_line: Splice Machine documentation

feedback_email: docs@splicemachine.com
# used as a contact email for the Feedback link in the top navigation bar

feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

# feedback_text: "Need help?"
# if you uncomment the previous line, it changes the Feedback text

# feedback_link: "http://helpy.io/"
# if you uncomment the previous line, it changes where the feedback link points to


highlighter: none
# library used for syntax highlighting

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: none
 enable_coderay: false
 syntax_highlighter_opts:
     disable: true

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways

collections:
  tooltips:
    output: false
# collections are declared here. this renders the content in _tooltips and processes it, but doesn't output it as actual files in the output unless you change output to true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: home_sidebar
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true
      sidebar: home_sidebar

description: "Documentation for Splice Machine."
# the description is used in the feed.xml file

# needed for sitemap.xml file only
url: https://doc.splicemachine.com
sitemap_url: https://doc.splicemachine.com

#google_analytics: Only used in doc build

build_type: doc
build_product: Customer Docs


incl_notpdf: true
incl_notyet: false
incl_onlypdf: false
incl_hidden: false

# Variables used for swiftype search script (includes/swiftype_install) and filter meta tag (includes/head.html)
#                     (Also used in our sidebar.html file)
build_version: "2.7"
site_search_id: "YGtH3zGt4NJzs35yCo5A"

pdf_runninghead: "Splice Machine Documentation"
guide_heading: "Splice Machine Documentation"
pdf_sidebar: " "
pdf_linkprefix: " "
