topnav_title: Splice Machine Internal Docs

# needed for sitemap.xml file only
url: https://docsdev.splicemachine.com

port: 4006

#google_analytics: Only used in doc build

# Conditional Include Variables for Docsdev Build
isbuild_doc: false
isbuild_docstest: false
isbuild_docsdev: true

incl_notpdf: true
incl_notyet: false
incl_onlypdf: false
incl_hidden: false

# Swiftype search engine id:
site_search_id: "YGtH3zGt4NJzs35yCo5A"
