topnav_title: Splice Machine Internal Docs

port: 4000

url: https://docstest.splicemachine.com
sitemap_url: https://docstest.splicemachine.com


#google_analytics: Only used in doc build


build_type: docstest
build_product: Internal Docs

incl_notpdf: true
incl_notyet: false
incl_onlypdf: false
incl_hidden: false

# Swiftype search engine id:
site_search_id: "YGtH3zGt4NJzs35yCo5A"
