topnav_title: Splice Machine Internal Docs

port: 4006

url: https://docsdev.splicemachine.com
sitemap_url: https://docsdev.splicemachine.com

#google_analytics: Only used in doc build

build_type: docsdev
build_product: Development Docs

incl_notpdf: true
incl_notyet: false
incl_onlypdf: false
incl_hidden: false

# Swiftype search engine id:
site_search_id: "YGtH3zGt4NJzs35yCo5A"
