topnav_title: Splice Machine Internal Docs

port: 4000

url: https://docstest.splicemachine.com
sitemap_url: https://docstest.splicemachine.com


#google_analytics: Only used in doc build

# Conditional Include Variables for Docstest Build
isbuild_doc: false
isbuild_docstest: true
isbuild_docsdev: false

incl_notpdf: true
incl_notyet: false
incl_onlypdf: false
incl_hidden: false

build_product: Splice Machine Internal

# Swiftype search engine id:
site_search_id: "YGtH3zGt4NJzs35yCo5A"
