topnav_title: Splice Machine Documentation

port: 4000

url: https://doc.splicemachine.com
sitemap_url: https://doc.splicemachine.com

google_analytics: UA-35630173-2

# Conditional Include Variables for Doc Build
isbuild_doc: true
isbuild_docstest: false
isbuild_docsdev: false

incl_notpdf: true
incl_notyet: false
incl_onlypdf: false
incl_hidden: false

build_product: Customer Docs

# Swiftype search engine id:
site_search_id: "eg_YmbQ_YzBTPNDdxQxT"
