#!/bin/sh

echo ""
echo "------------------------------------------------------------------------"
echo "---                                                                  ---"
echo "---   IF YOU'VE CHANGED THE SIDEBAR, BEFORE BUILDING A VERSION TO BE ---"
echo "---   DEPLOYED ONLINE, YOU MUST:                                     ---"
echo "---      1. Build the web locally                                    ---"
echo "---      2. Start the web locally                                    ---"
echo "---      3. Capture the output of Generate_PageNav_Yaml.html page    ---"
echo "---      4. Paste that output into data/pagenextprev_nav.yml         ---"
echo "---                                                                  ---"
echo "------------------------------------------------------------------------"
echo ""

PS3="Select which Docs Version to build: "
COLUMNS=12
OPTIONS=( 'DocsDev 3.0'
          'DocsTest 3.0'
          'DocsTest 2.8'
          'DocsTest 2.7'
          'Doc 3.0'
          'Doc 2.8'
          'Doc 2.7'
          'Doc 2.5' )
select opt in "${OPTIONS[@]}"; do
    case $opt in
        'DocsDev 3.0')
            version='docsdev'
            branch='3.0'
            break;
            ;;
        'DocsTest 3.0')
            version='docstest'
            branch='3.0'
            break;
            ;;
        'DocsTest 2.8')
            version='docstest'
            branch='2.8'
            break;
            ;;
        'DocsTest 2.7')
            version='docstest'
            branch='2.7'
            break;
            ;;
        'Doc 3.0')
            version='doc'
            branch='3.0'
            break;
            ;;
        'Doc 2.8')
            version='doc'
            branch='2.8'
            break;
            ;;
        'Doc 2.7')
            version='doc'
            branch='2.7'
            break;
            ;;
        'Doc 2.5')
            version='doc'
            branch='2.5'
            break;
            ;;
        *) echo Invalid option;;
    esac
done

echo "Killing all Jekyll instances"
kill -9 $(ps aux | grep '[j]ekyll' | awk '{print $2}')

echo "  --> Building with _config.yml,_config_$version.yml,_config_$branch.yml"

echo "Building Splice Documentation HTML suite"
 jekyll serve --detach --config _config.yml,_config_$version.yml,_config_$branch.yml,pdfconfigs/suite/config_pdf.yml
echo "done"

echo "Creating PDF file: pdf/splicedocs.pdf"
 mkdir -m777 _site/pdf
 prince --javascript --input-list=_site/pdfconfigs/suite/prince-list.txt -o _site/pdf/splicedocs.pdf 2>_site/pdf/pdfwarns.txt
echo "done"

# say -v Fiona "$version $branch PDF Done"
