#!/bin/sh


echo "Killing all Jekyll instances"
kill -9 $(ps aux | grep '[j]ekyll' | awk '{print $2}')

echo "Building Splice Test HTML site"
 jekyll serve --detach --config _config.yml,_config_2.7.yml,_config_doc.yml,pdfconfigs/config_testpdf.yml
echo "done"

echo "Creating PDF file: pdf/splicetest.pdf"
# prince --capture=princetest --javascript --input-list=_site/pdfconfigs/prince-testlist.txt -o pdf/splicetest.pdf 2>pdfwarns.txt
 prince --javascript --input-list=_site/pdfconfigs/prince-testlist.txt -o pdf/splicetest.pdf 2>pdfwarns.txt
echo "done"

afplay /System/Library/Sounds/Ping.aiff
