#!/bin/sh
read -p "Enter the version to build (doc, docstest, docsdev)      [docsdev]: " version
version=${version:-docsdev}

if [ $version = 'doc' ]
then
    read -p "Enter the branch to build (2.5)    [2.5]: " branch
branch=${branch:-2.5}
else
    branch='2.5'
fi


echo "Will generate sitemap file: _site/sitemap.$branch.xml"

jekyll serve --config=_config.yml,_config_$version.yml,_config_$branch.yml

# When generating a previous version, we:
#   a. need to use a different sitemapgen file that includes the directory in each generated URL
#   b. we DO NOT want to overwrite the main sitemap.xml (sitemapindex) file
mv _site/sitemapgen.$branch.xml _site/sitemap.$branch.xml
