destination: _site/
url: "http://127.0.0.1:4010"
baseurl: ""
port: 4010
output: pdf
product: all
print_title: Developer's Guide
guide_heading:  Splice Machine Developer's Guide
print_subtitle:
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: developers_sidebar
