CREATE SCHEMA SPLICEANSWERS;

SET CURRENT SCHEMA = SPLICEANSWERS;

CREATE TABLE SPLICEANSWERS.QUESTIONS (
ID  INTEGER NOT NULL PRIMARY KEY  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
QUESTION VARCHAR(512) NOT NULL,
ANSWER VARCHAR(4096) NOT NULL,
APPLIES VARCHAR(512) NOT NULL,
CATEGORYID INT NOT NULL,
INTERNALONLY BOOLEAN );


CREATE TABLE SPLICEANSWERS.CATEGORIES (
ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NAME VARCHAR(128) NOT NULL,
PARENT INTEGER );

CREATE TABLE SPLICEANSWERS.LINKS (
QUESTIONID INTEGER NOT NULL PRIMARY KEY,
RELATEDID INTEGER NOT NULL,
TYPEID INTEGER DEFAULT 0);

CREATE TABLE SPLICEANSWERS.LINKTYPES (
ID INTEGER NOT NULL PRIMARY KEY,
TYPENAME VARCHAR(32) );


INSERT INTO SPLICEANSWERS.LINKTYPES VALUES (0, 'To'), (1, 'From'), (2, 'Both');
