destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/"
port: 4010
output: pdf
product: all
print_title: Database-as-Service
print_subtitle:
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: dbaas_sidebar
